### ISSUE TITLE
Ceph-Mon runs before ceph has installed

### ISSUE THREAD

**Issue by JasonQuinn** [datacentred/puppet-ceph#1]
I included ceph in my manifest with `include ::ceph` and used the same hiera config as listed in the read me and got the error message -
`Error: Validation of Exec[ceph-mon --mkfs -i archive --key AQA7yNlUMy3sFhAA62XHf57L0QhSI44qqqOVXA==] failed: 'ceph-mon --mkfs -i archive --key AQA7yNlUMy3sFhAA62XHf57L0QhSI44qqqOVXA==' is not qualified and no path was specified. Please qualify the command or specify a path. at /tmp/vagrant-puppet/modules-6274ef4681525a3adbd04a0344ddcbac/ceph/manifests/mon.pp:14`

When I look at the box ceph has not been installed.

If I change the hiera config to `ceph::mon: false` then ceph gets installed but then obviously has no monitor.

**Comment by spjmurray** [comment]
My bad, I should update the documentation.  In your site.pp you will need a snippet that does the following:

``` puppet
Exec {
  path => '/bin:/usr/bin:/sbin:/usr/sbin',
}
```

**Comment by spjmurray** [comment]
Addressed by commit 0cf21e2fa54d218bb132f46206eb91dc5495e836 and released in v1.3.1
